version: "3.7"

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=mealschedule
      - POSTGRES_DB=mealplan
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: meal_plan
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on: 
      - database

volumes:
  pgdata:
    driver: local